name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet .

    - name: Test
      run: go test -v -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
